# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160824_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('date_test', models.DateTimeField(verbose_name='Test published')),
            ],
        ),
    ]
